/**
 * fsh
 * File server hosting
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: manuelcolombini@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileFieldsOneOf } from './fileFieldsOneOf';


/**
 * @type FileFields
 * @export
 */
export type FileFields = FileFieldsOneOf | Set<string>;

