/**
 * fsh
 * File server hosting
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: manuelcolombini@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    username: string;
    name: string;
    lastname: string;
    id?: string;
    password: string;
}

